service: robot-api

package:
  individually: true

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  stage: ${opt:stage, "dev"}

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: false
    layer:
      name: robot-layer
      description: The robot's layer
      CompatibleRuntimes:
        - python3.8

functions:
  app:
    package:
      patterns:
        - "bfcm.py"
        - ! "requirements.txt"
        - ! "package.json"
        - ! "package-lock.json"
        - ! ".serverles/**"
        - ! ".virtualenv/**"
        - ! "node_modules/**"
    handler: bfcm.handler
    environment:
      STAGE: ${self:provider.stage}
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          method: any
          path: /{proxy+}